### ISSUE TITLE
About translation model

### ISSUE THREAD

**Issue by Heaven-zhw** [UKPLab/mdl-stance-robustness#3]
https://github.com/UKPLab/mdl-stance-robustness/blob/68a606556f2492945be4c6623650f5bc17daa36e/data_utils/glue_utils.py#L279

This error occerred at the above line when I created the data for adversarial test sets : 
              FileNotFoundError: [Errno 2] No such file or directory: 'translation_models/premises-en.txt'

So where can I find the model directory and files? I've already set up OpenNMT-py as the document says.

**Comment by v1nc3nt27** [comment]
Did you download the translation models and extracted them into the project directory (see the download.sh, line 32)?

**Comment by Heaven-zhw** [comment]
> Did you download the translation models and extracted them into the project directory (see the download.sh, line 32)?

Yes, I have executed the script file "download.sh". Just now I executed these commands (download.sh, line 32-34) individually, and successfully got the files. Maybe I deleted the model directory by mistake then. Thanks!
